import { auth, currentUser } from "@clerk/nextjs/server";
import Link from "next/link";

const STATS = [
  { label: "Active Projects", value: "12", change: "+2 this week", up: true },
  { label: "Monthly Revenue", value: "$4,280", change: "+18% vs last month", up: true },
  { label: "Team Members", value: "8", change: "2 pending invites", up: false },
  { label: "API Calls", value: "142k", change: "+34% vs last month", up: true },
];

const ACTIVITY = [
  { time: "2 min ago", text: "New signup from jane@example.com", icon: "👤" },
  { time: "14 min ago", text: "Payment of $29 received (Pro plan)", icon: "💳" },
  { time: "1 hr ago", text: "Webhook delivered to api.yourapp.com", icon: "🔗" },
  { time: "3 hr ago", text: "Database backup completed (2.4 GB)", icon: "💾" },
  { time: "5 hr ago", text: "New API key generated by admin@example.com", icon: "🔑" },
];

export default async function DashboardPage() {
  const user = await currentUser();

  return (
    <div style={{ minHeight: "100vh", backgroundColor: "var(--background)" }}>
      {/* Sidebar + main layout */}
      <div style={{ display: "flex" }}>
        {/* Sidebar */}
        <aside
          style={{
            width: 240,
            minHeight: "100vh",
            backgroundColor: "var(--surface)",
            borderRight: "1px solid var(--border)",
            padding: "24px 0",
            position: "fixed",
            top: 0,
            left: 0,
            display: "flex",
            flexDirection: "column",
          }}
        >
          <div style={{ padding: "0 20px 24px", borderBottom: "1px solid var(--border)" }}>
            <span style={{ fontWeight: 800, fontSize: 20, color: "var(--accent)" }}>
              ◆ SaaSify
            </span>
          </div>
          <nav style={{ padding: "16px 12px", flex: 1 }}>
            {[
              { icon: "◈", label: "Overview", href: "/dashboard", active: true },
              { icon: "📊", label: "Analytics", href: "/dashboard/analytics", active: false },
              { icon: "💳", label: "Billing", href: "/billing", active: false },
              { icon: "👥", label: "Team", href: "/dashboard/team", active: false },
              { icon: "⚙️", label: "Settings", href: "/settings", active: false },
            ].map((item) => (
              <Link
                key={item.label}
                href={item.href}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 10,
                  padding: "10px 12px",
                  borderRadius: "var(--radius-md)",
                  textDecoration: "none",
                  fontSize: 14,
                  fontWeight: item.active ? 600 : 500,
                  color: item.active ? "var(--accent)" : "var(--muted)",
                  backgroundColor: item.active ? "var(--accent-subtle)" : "transparent",
                  marginBottom: 4,
                }}
              >
                <span>{item.icon}</span>
                {item.label}
              </Link>
            ))}
          </nav>
          <div
            style={{
              padding: "16px 20px",
              borderTop: "1px solid var(--border)",
              fontSize: 13,
              color: "var(--muted)",
            }}
          >
            <div style={{ fontWeight: 600, color: "var(--foreground)", marginBottom: 2 }}>
              {user?.firstName || "User"} {user?.lastName || ""}
            </div>
            <div style={{ wordBreak: "break-all" }}>
              {user?.emailAddresses[0]?.emailAddress || "user@example.com"}
            </div>
          </div>
        </aside>

        {/* Main content */}
        <main style={{ marginLeft: 240, flex: 1, padding: 32 }}>
          {/* Header */}
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              marginBottom: 32,
            }}
          >
            <div>
              <h1 style={{ fontSize: 28, fontWeight: 800, letterSpacing: "-0.02em", marginBottom: 4 }}>
                Good morning, {user?.firstName || "there"} 👋
              </h1>
              <p style={{ color: "var(--muted)" }}>
                Here&apos;s what&apos;s happening with your workspace today.
              </p>
            </div>
            <Link
              href="/billing"
              style={{
                backgroundColor: "var(--accent)",
                color: "#fff",
                padding: "10px 20px",
                borderRadius: "var(--radius-md)",
                textDecoration: "none",
                fontWeight: 600,
                fontSize: 14,
                boxShadow: "0 2px 12px rgba(108,71,255,0.3)",
              }}
            >
              Upgrade plan →
            </Link>
          </div>

          {/* Stats grid */}
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
              gap: 20,
              marginBottom: 32,
            }}
          >
            {STATS.map((stat) => (
              <div
                key={stat.label}
                style={{
                  backgroundColor: "var(--surface)",
                  border: "1px solid var(--border)",
                  borderRadius: "var(--radius-lg)",
                  padding: 24,
                  boxShadow: "var(--shadow-sm)",
                }}
              >
                <p style={{ color: "var(--muted)", fontSize: 13, fontWeight: 500, marginBottom: 8 }}>
                  {stat.label}
                </p>
                <p
                  style={{
                    fontSize: 32,
                    fontWeight: 800,
                    letterSpacing: "-0.03em",
                    color: "var(--foreground)",
                    marginBottom: 8,
                  }}
                >
                  {stat.value}
                </p>
                <p
                  style={{
                    fontSize: 12,
                    color: stat.up ? "var(--success)" : "var(--muted)",
                    fontWeight: 500,
                  }}
                >
                  {stat.up ? "↑ " : ""}{stat.change}
                </p>
              </div>
            ))}
          </div>

          {/* Activity feed */}
          <div
            style={{
              backgroundColor: "var(--surface)",
              border: "1px solid var(--border)",
              borderRadius: "var(--radius-lg)",
              padding: 24,
              boxShadow: "var(--shadow-sm)",
            }}
          >
            <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 20 }}>
              Recent Activity
            </h2>
            <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
              {ACTIVITY.map((item, i) => (
                <div
                  key={i}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 14,
                    padding: "14px 0",
                    borderBottom: i < ACTIVITY.length - 1 ? "1px solid var(--border)" : "none",
                  }}
                >
                  <div
                    style={{
                      width: 38,
                      height: 38,
                      borderRadius: "var(--radius-md)",
                      backgroundColor: "var(--accent-subtle)",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      fontSize: 18,
                      flexShrink: 0,
                    }}
                  >
                    {item.icon}
                  </div>
                  <div style={{ flex: 1 }}>
                    <p style={{ fontSize: 14, fontWeight: 500, color: "var(--foreground)" }}>
                      {item.text}
                    </p>
                    <p style={{ fontSize: 12, color: "var(--muted)", marginTop: 2 }}>{item.time}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
